#!/usr/bin/env python3
# -*- coding: utf8 -*-

"""Usage: moviesrt [options] INFILE [SRTFILE]

Options:
  -h --help                Show this screen.
  -l <lang> --lang=<lang>  Language of the subtitles. Defaults to "English".
  -o <file> --out=<file>   The output file. Defaults to "out.mkv".
"""
import sys
import subprocess
import docopt
import shlex

# The template for the command we will run on the input files.
cmdtemplate = 'mkvmerge -o {} --default-track 0 --language 0:{} {} {}'

def main():
    arguments = docopt.docopt(__doc__)
    
    lang = arguments['--lang']
    outfile = arguments['--out']
    infile = arguments['INFILE']
    srtfile = arguments['SRTFILE']
    
    if not lang: lang = 'English'
    if not outfile: outfile = 'out.mkv'
    if not srtfile:
        # Subtract suffix from infile
        srtfile = infile.rsplit('.', 1)[0]
        srtfile += '.srt'
    
    lang = shlex.quote(lang)
    infile = shlex.quote(infile)
    srtfile = shlex.quote(srtfile)
    
    #print("in: {}\nout: {}\nsrt: {}\nlang: {}".format(
    #    infile, outfile, srtfile, lang
    #))
    #return 0 
    cmd = cmdtemplate.format(outfile, lang, srtfile, infile)
    return subprocess.call(cmd, shell=True)


if __name__ == '__main__':
    sys.exit(main())
